# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_MODEL_01.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainFrame(object):
    def setupUi(self, MainFrame):
        MainFrame.setObjectName("MainFrame")
        MainFrame.resize(1332, 684)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        MainFrame.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainFrame)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1300, 700))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 471, 415))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.AB_INPUT_LAYOUT = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.AB_INPUT_LAYOUT.setContentsMargins(0, 0, 0, 0)
        self.AB_INPUT_LAYOUT.setObjectName("AB_INPUT_LAYOUT")
        self.AB_LABEL_INTERVAL = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(24)
        font.setBold(True)
        self.AB_LABEL_INTERVAL.setFont(font)
        self.AB_LABEL_INTERVAL.setObjectName("AB_LABEL_INTERVAL")
        self.AB_INPUT_LAYOUT.addWidget(self.AB_LABEL_INTERVAL)
        self.AB_INPUT_INTERVAL = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        self.AB_INPUT_INTERVAL.setFont(font)
        self.AB_INPUT_INTERVAL.setObjectName("AB_INPUT_INTERVAL")
        self.AB_INPUT_LAYOUT.addWidget(self.AB_INPUT_INTERVAL)
        self.AB_BUTTON_INTERVAL = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        self.AB_BUTTON_INTERVAL.setFont(font)
        self.AB_BUTTON_INTERVAL.setObjectName("AB_BUTTON_INTERVAL")
        self.AB_INPUT_LAYOUT.addWidget(self.AB_BUTTON_INTERVAL)
        self.AB_LABEL_PUNCT = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(20)
        font.setBold(True)
        self.AB_LABEL_PUNCT.setFont(font)
        self.AB_LABEL_PUNCT.setObjectName("AB_LABEL_PUNCT")
        self.AB_INPUT_LAYOUT.addWidget(self.AB_LABEL_PUNCT)
        self.AB_SLIDER_PUNCT = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.AB_SLIDER_PUNCT.setOrientation(QtCore.Qt.Horizontal)
        self.AB_SLIDER_PUNCT.setObjectName("AB_SLIDER_PUNCT")
        self.AB_INPUT_LAYOUT.addWidget(self.AB_SLIDER_PUNCT)
        self.AB_LABEL_GRAD = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.AB_LABEL_GRAD.setFont(font)
        self.AB_LABEL_GRAD.setObjectName("AB_LABEL_GRAD")
        self.AB_INPUT_LAYOUT.addWidget(self.AB_LABEL_GRAD)
        self.AB_SLIDER = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.AB_SLIDER.setOrientation(QtCore.Qt.Horizontal)
        self.AB_SLIDER.setObjectName("AB_SLIDER")
        self.AB_INPUT_LAYOUT.addWidget(self.AB_SLIDER)
        self.AB_BUTTON_CALCULEAZA = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(True)
        self.AB_BUTTON_CALCULEAZA.setFont(font)
        self.AB_BUTTON_CALCULEAZA.setObjectName("AB_BUTTON_CALCULEAZA")
        self.AB_INPUT_LAYOUT.addWidget(self.AB_BUTTON_CALCULEAZA)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 440, 471, 141))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_layout_play = QtWidgets.QHBoxLayout()
        self.button_layout_play.setObjectName("button_layout_play")
        self.AB_BUTTON_PLAY = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        self.AB_BUTTON_PLAY.setFont(font)
        self.AB_BUTTON_PLAY.setObjectName("AB_BUTTON_PLAY")
        self.button_layout_play.addWidget(self.AB_BUTTON_PLAY)
        self.verticalLayout.addLayout(self.button_layout_play)
        self.AB_LABEL_OUTPUT = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(20)
        font.setBold(True)
        self.AB_LABEL_OUTPUT.setFont(font)
        self.AB_LABEL_OUTPUT.setObjectName("AB_LABEL_OUTPUT")
        self.verticalLayout.addWidget(self.AB_LABEL_OUTPUT)
        self.OUTPUT_textfield = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.OUTPUT_textfield.setFont(font)
        self.OUTPUT_textfield.setObjectName("OUTPUT_textfield")
        self.verticalLayout.addWidget(self.OUTPUT_textfield)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(20)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.OUTPUTERROR_textfield_ = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        self.OUTPUTERROR_textfield_.setFont(font)
        self.OUTPUTERROR_textfield_.setObjectName("OUTPUTERROR_textfield_")
        self.verticalLayout.addWidget(self.OUTPUTERROR_textfield_)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(490, 10, 691, 611))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.AB_WIG_GRAF = QtWidgets.QWidget(self.gridLayoutWidget_2)
        self.AB_WIG_GRAF.setObjectName("AB_WIG_GRAF")
        self.gridLayout.addWidget(self.AB_WIG_GRAF, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(310, 160, 871, 451))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.IL_WIG_GRAF = QtWidgets.QWidget(self.gridLayoutWidget_3)
        self.IL_WIG_GRAF.setObjectName("IL_WIG_GRAF")
        self.gridLayout_2.addWidget(self.IL_WIG_GRAF, 0, 0, 1, 1)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 291, 591))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.IL_LABEL_INTERVAL = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.IL_LABEL_INTERVAL.setFont(font)
        self.IL_LABEL_INTERVAL.setObjectName("IL_LABEL_INTERVAL")
        self.verticalLayout_2.addWidget(self.IL_LABEL_INTERVAL)
        self.IL_TEXTFIELD_INTERVAL = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.IL_TEXTFIELD_INTERVAL.setObjectName("IL_TEXTFIELD_INTERVAL")
        self.verticalLayout_2.addWidget(self.IL_TEXTFIELD_INTERVAL)
        self.IL_LABEL_NODURI = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.IL_LABEL_NODURI.setFont(font)
        self.IL_LABEL_NODURI.setObjectName("IL_LABEL_NODURI")
        self.verticalLayout_2.addWidget(self.IL_LABEL_NODURI)
        self.IL_TEXTFIELD_NODURI = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.IL_TEXTFIELD_NODURI.setObjectName("IL_TEXTFIELD_NODURI")
        self.verticalLayout_2.addWidget(self.IL_TEXTFIELD_NODURI)
        self.IL_TABEL = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.IL_TABEL.setObjectName("IL_TABEL")
        self.IL_TABEL.setColumnCount(2)
        self.IL_TABEL.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.IL_TABEL.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IL_TABEL.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IL_TABEL.setHorizontalHeaderItem(1, item)
        self.verticalLayout_2.addWidget(self.IL_TABEL)
        self.IL_BUTTON_ADAUGA = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        self.IL_BUTTON_ADAUGA.setFont(font)
        self.IL_BUTTON_ADAUGA.setObjectName("IL_BUTTON_ADAUGA")
        self.verticalLayout_2.addWidget(self.IL_BUTTON_ADAUGA)
        self.IL_BUTTON_PLAY = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        self.IL_BUTTON_PLAY.setFont(font)
        self.IL_BUTTON_PLAY.setObjectName("IL_BUTTON_PLAY")
        self.verticalLayout_2.addWidget(self.IL_BUTTON_PLAY)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(310, 10, 871, 141))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.IL_LABEL_OUTPUT = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(15)
        font.setBold(True)
        self.IL_LABEL_OUTPUT.setFont(font)
        self.IL_LABEL_OUTPUT.setObjectName("IL_LABEL_OUTPUT")
        self.verticalLayout_13.addWidget(self.IL_LABEL_OUTPUT)
        self.IL_TEXTFIELD_OUTPUT = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.IL_TEXTFIELD_OUTPUT.setObjectName("IL_TEXTFIELD_OUTPUT")
        self.verticalLayout_13.addWidget(self.IL_TEXTFIELD_OUTPUT)
        self.IL_LABEL_OUTPUT_ERROR = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(15)
        font.setBold(True)
        self.IL_LABEL_OUTPUT_ERROR.setFont(font)
        self.IL_LABEL_OUTPUT_ERROR.setObjectName("IL_LABEL_OUTPUT_ERROR")
        self.verticalLayout_13.addWidget(self.IL_LABEL_OUTPUT_ERROR)
        self.IL_TEXTFIELD_ERROR = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.IL_TEXTFIELD_ERROR.setObjectName("IL_TEXTFIELD_ERROR")
        self.verticalLayout_13.addWidget(self.IL_TEXTFIELD_ERROR)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(320, 470, 861, 149))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.IS_LABEL_OUTPUT = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(16)
        font.setBold(True)
        self.IS_LABEL_OUTPUT.setFont(font)
        self.IS_LABEL_OUTPUT.setObjectName("IS_LABEL_OUTPUT")
        self.verticalLayout_8.addWidget(self.IS_LABEL_OUTPUT)
        self.IS_TEXTFIELD_OUTPUT = QtWidgets.QLineEdit(self.verticalLayoutWidget_11)
        self.IS_TEXTFIELD_OUTPUT.setObjectName("IS_TEXTFIELD_OUTPUT")
        self.verticalLayout_8.addWidget(self.IS_TEXTFIELD_OUTPUT)
        self.IS_LABEL_OUTERROR = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(16)
        font.setBold(True)
        self.IS_LABEL_OUTERROR.setFont(font)
        self.IS_LABEL_OUTERROR.setObjectName("IS_LABEL_OUTERROR")
        self.verticalLayout_8.addWidget(self.IS_LABEL_OUTERROR)
        self.IS_TEXTFIELD_ERROR = QtWidgets.QLineEdit(self.verticalLayoutWidget_11)
        self.IS_TEXTFIELD_ERROR.setObjectName("IS_TEXTFIELD_ERROR")
        self.verticalLayout_8.addWidget(self.IS_TEXTFIELD_ERROR)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(310, 10, 861, 441))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.IS_WIG_GRAF = QtWidgets.QWidget(self.gridLayoutWidget_4)
        self.IS_WIG_GRAF.setObjectName("IS_WIG_GRAF")
        self.gridLayout_3.addWidget(self.IS_WIG_GRAF, 0, 0, 1, 1)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_3)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 291, 601))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.IS_LABEL_INTERVAL_ = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.IS_LABEL_INTERVAL_.setFont(font)
        self.IS_LABEL_INTERVAL_.setObjectName("IS_LABEL_INTERVAL_")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.IS_LABEL_INTERVAL_)
        self.IS_TEXTFIELD_INTERVAL = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.IS_TEXTFIELD_INTERVAL.setObjectName("IS_TEXTFIELD_INTERVAL")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.IS_TEXTFIELD_INTERVAL)
        self.IS_LABEL_NODURI = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.IS_LABEL_NODURI.setFont(font)
        self.IS_LABEL_NODURI.setObjectName("IS_LABEL_NODURI")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.IS_LABEL_NODURI)
        self.IS_TEXTFIELD_NODURI = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.IS_TEXTFIELD_NODURI.setObjectName("IS_TEXTFIELD_NODURI")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.IS_TEXTFIELD_NODURI)
        self.IL_TABEL_2 = QtWidgets.QTableWidget(self.formLayoutWidget_2)
        self.IL_TABEL_2.setObjectName("IL_TABEL_2")
        self.IL_TABEL_2.setColumnCount(2)
        self.IL_TABEL_2.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.IL_TABEL_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IL_TABEL_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IL_TABEL_2.setHorizontalHeaderItem(1, item)
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.IL_TABEL_2)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.IS_LABEL_TIP = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(15)
        font.setBold(True)
        self.IS_LABEL_TIP.setFont(font)
        self.IS_LABEL_TIP.setObjectName("IS_LABEL_TIP")
        self.verticalLayout_12.addWidget(self.IS_LABEL_TIP)
        self.IS_RADIO_LINIAR = QtWidgets.QRadioButton(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        self.IS_RADIO_LINIAR.setFont(font)
        self.IS_RADIO_LINIAR.setObjectName("IS_RADIO_LINIAR")
        self.verticalLayout_12.addWidget(self.IS_RADIO_LINIAR)
        self.IS_RADIO_PATRATIC = QtWidgets.QRadioButton(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        self.IS_RADIO_PATRATIC.setFont(font)
        self.IS_RADIO_PATRATIC.setObjectName("IS_RADIO_PATRATIC")
        self.verticalLayout_12.addWidget(self.IS_RADIO_PATRATIC)
        self.IS_RADIO_CUBIC = QtWidgets.QRadioButton(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        self.IS_RADIO_CUBIC.setFont(font)
        self.IS_RADIO_CUBIC.setObjectName("IS_RADIO_CUBIC")
        self.verticalLayout_12.addWidget(self.IS_RADIO_CUBIC)
        self.IS_BUTTON_CALCULEAZA = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.IS_BUTTON_CALCULEAZA.setObjectName("IS_BUTTON_CALCULEAZA")
        self.verticalLayout_12.addWidget(self.IS_BUTTON_CALCULEAZA)
        self.formLayout_2.setLayout(3, QtWidgets.QFormLayout.SpanningRole, self.verticalLayout_12)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.tab_5)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(0, 10, 1191, 611))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.gridLayoutWidget_6)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.textEdit = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 1181, 571))
        self.textEdit.setObjectName("textEdit")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_7)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 1191, 571))
        self.textBrowser.setObjectName("textBrowser")
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab_6)
        self.textBrowser_2.setGeometry(QtCore.QRect(0, 0, 1181, 571))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_8)
        self.textEdit_2.setGeometry(QtCore.QRect(0, 0, 1191, 581))
        self.textEdit_2.setObjectName("textEdit_2")
        self.tabWidget_2.addTab(self.tab_8, "")
        self.gridLayout_5.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        MainFrame.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainFrame)
        self.statusbar.setObjectName("statusbar")
        MainFrame.setStatusBar(self.statusbar)

        self.retranslateUi(MainFrame)
        self.tabWidget.setCurrentIndex(3)
        self.tabWidget_2.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainFrame)

    def retranslateUi(self, MainFrame):
        _translate = QtCore.QCoreApplication.translate
        MainFrame.setWindowTitle(_translate("MainFrame", "Polinoame de aproximare si de interpolare."))
        self.AB_LABEL_INTERVAL.setText(_translate("MainFrame", "Interval [a,b]"))
        self.AB_BUTTON_INTERVAL.setText(_translate("MainFrame", "Set Interval"))
        self.AB_LABEL_PUNCT.setText(_translate("MainFrame", "Punct"))
        self.AB_LABEL_GRAD.setText(_translate("MainFrame", "Grad:"))
        self.AB_BUTTON_CALCULEAZA.setText(_translate("MainFrame", "Calculează"))
        self.AB_BUTTON_PLAY.setText(_translate("MainFrame", "▶"))
        self.AB_LABEL_OUTPUT.setText(_translate("MainFrame", "Output F(X)"))
        self.label_11.setText(_translate("MainFrame", "Output Error"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainFrame", "Aproximare Bernstein"))
        self.IL_LABEL_INTERVAL.setText(_translate("MainFrame", "Interval [a,b]"))
        self.IL_LABEL_NODURI.setText(_translate("MainFrame", "NrNoduri"))
        item = self.IL_TABEL.verticalHeaderItem(0)
        item.setText(_translate("MainFrame", "Variabile"))
        item = self.IL_TABEL.horizontalHeaderItem(0)
        item.setText(_translate("MainFrame", "X"))
        item = self.IL_TABEL.horizontalHeaderItem(1)
        item.setText(_translate("MainFrame", "Y"))
        self.IL_BUTTON_ADAUGA.setText(_translate("MainFrame", "Calculează"))
        self.IL_BUTTON_PLAY.setText(_translate("MainFrame", "▶"))
        self.IL_LABEL_OUTPUT.setText(_translate("MainFrame", "Output F(X)"))
        self.IL_LABEL_OUTPUT_ERROR.setText(_translate("MainFrame", "Output Error"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainFrame", "Interpolare Lagrange"))
        self.IS_LABEL_OUTPUT.setText(_translate("MainFrame", "Output F(X)"))
        self.IS_LABEL_OUTERROR.setText(_translate("MainFrame", "Output Error"))
        self.IS_LABEL_INTERVAL_.setText(_translate("MainFrame", "Interval [a,b]"))
        self.IS_LABEL_NODURI.setText(_translate("MainFrame", "NrNoduri"))
        item = self.IL_TABEL_2.verticalHeaderItem(0)
        item.setText(_translate("MainFrame", "Variabile"))
        item = self.IL_TABEL_2.horizontalHeaderItem(0)
        item.setText(_translate("MainFrame", "X"))
        item = self.IL_TABEL_2.horizontalHeaderItem(1)
        item.setText(_translate("MainFrame", "Y"))
        self.IS_LABEL_TIP.setText(_translate("MainFrame", "Spline Tip"))
        self.IS_RADIO_LINIAR.setText(_translate("MainFrame", "Liniar"))
        self.IS_RADIO_PATRATIC.setText(_translate("MainFrame", "Pătratic"))
        self.IS_RADIO_CUBIC.setText(_translate("MainFrame", "Cubic"))
        self.IS_BUTTON_CALCULEAZA.setText(_translate("MainFrame", "Calculează"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainFrame", "Interpolare Spline"))
        self.textEdit.setHtml(_translate("MainFrame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt; font-weight:600;\">Noțiuni Teoretice </span><span style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\"><br /><br />Polinoamele Bernstein sunt utilizate pentru a aproxima o funcție continuă pe un interval închis [a, b]. Spre deosebire de interpolare, curba rezultată nu trece neapărat prin punctele de control, dar oferă o aproximare netedă și convergentă. Pe măsură ce gradul (n) al polinomului crește, curba de aproximare se apropie din ce în ce mai mult de forma funcției originale. <br /><br /></span><span style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt; font-weight:600;\">Ghid de Utilizare</span></p>\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Introduceți Intervalul:</span> În câmpul <span style=\" font-family:\'monospace\';\">Interval [a,b]</span>, tastați capetele intervalului de studiu (de exemplu, <span style=\" font-family:\'monospace\';\">0, 10</span>) și apăsați butonul <span style=\" font-weight:600;\">&quot;Set Interval&quot;</span>.</li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Introduceți Punctul:</span> În câmpul <span style=\" font-family:\'monospace\';\">Punct</span>, introduceți valoarea <span style=\" font-family:\'monospace\';\">x</span> pentru care doriți să calculați valoarea aproximată a funcției.</li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Setați Gradul:</span> În câmpul <span style=\" font-family:\'monospace\';\">Grad</span>, introduceți gradul <span style=\" font-family:\'monospace\';\">n</span> al polinomului Bernstein pe care doriți să-l utilizați. Un grad mai mare va duce la o aproximare mai precisă, dar necesită mai mult calcul.</li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Calculați:</span> Apăsați butonul <span style=\" font-weight:600;\">&quot;Calculează&quot;</span></li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Vizualizați Rezultatele:</span> \n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\">\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'monospace\';\">Output F(X)</span>: Va afișa valoarea polinomului Bernstein în punctul <span style=\" font-family:\'monospace\';\">x</span> specificat.</li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'monospace\';\">Output Error</span>: Va afișa eroarea de aproximare, calculată ca diferența dintre valoarea reală a funcției (dacă este cunoscută) și valoarea aproximată.</li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Graficul din dreapta va afișa funcția originală și polinomul de aproximare.</li></ul></li></ol></body></html>"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainFrame", "Aproximare Bernstein"))
        self.textBrowser.setHtml(_translate("MainFrame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><title>Ghid: Interpolare Lagrange</title><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<h2 style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt; font-weight:600;\">Interpolare Lagrange</span></h2>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\">Interpolarea Lagrange este o metodă de a găsi un </span><span style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt; font-weight:600;\">polinom unic</span><span style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\"> de grad minim care trece </span><span style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt; font-weight:600;\">exact</span><span style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\"> printr-un set dat de puncte (noduri). Dacă avem </span><span style=\" font-family:\'monospace\'; font-size:14pt;\">n+1</span><span style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\"> puncte distincte, polinomul Lagrange rezultat va avea un grad de cel mult </span><span style=\" font-family:\'monospace\'; font-size:14pt;\">n</span><span style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\">. Această metodă este utilă pentru a modela o funcție atunci când cunoaștem valoarea ei doar în câteva puncte discrete.<br /><br /><br /></span><span style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt; font-weight:600;\">Ghid de Utilizare</span></p>\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Introduceți Intervalul:</span> În câmpul <span style=\" font-family:\'monospace\';\">Interval [a,b]</span>, tastați capetele intervalului pe care va fi afișat graficul (de exemplu, <span style=\" font-family:\'monospace\';\">-5, 5</span>).</li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Setați Numărul de Noduri:</span> În câmpul <span style=\" font-family:\'monospace\';\">NrNoduri</span>, introduceți numărul de puncte de interpolare pe care le veți folosi.</li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Introduceți Nodurile:</span> În tabelul <span style=\" font-family:\'monospace\';\">Variabile</span>, completați coordonatele <span style=\" font-family:\'monospace\';\">X</span> și <span style=\" font-family:\'monospace\';\">Y</span> pentru fiecare nod. Numărul de rânduri disponibile va fi determinat de valoarea din <span style=\" font-family:\'monospace\';\">NrNoduri</span>.</li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Calculați:</span> Apăsați butonul <span style=\" font-weight:600;\">&quot;Calculează&quot;</span>.</li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Vizualizați Rezultatele:</span> \n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\">\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'monospace\';\">Output F(X)</span>: Va afișa expresia matematică a polinomului Lagrange rezultat.</li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'monospace\';\">Output Error</span>: Poate afișa informații despre eroarea de interpolare, dacă se compară cu o funcție cunoscută.</li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Graficul din dreapta va afișa punctele (nodurile) introduse și polinomul de interpolare care trece prin ele.</li></ul></li></ol></body></html>"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainFrame", "Interpolare Lagrange"))
        self.textBrowser_2.setHtml(_translate("MainFrame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<h2 style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt; font-weight:600;\">Interpolare Spline</span></h2>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt; font-weight:600;\">Noțiuni Teoretice</span></h3>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\">Interpolarea Spline este o tehnică avansată de interpolare care utilizează polinoame de grad mic pe sub-intervale (între noduri consecutive) și le unește astfel încât joncțiunea să fie netedă. Acest lucru evită oscilațiile mari care pot apărea la polinoamele Lagrange de grad înalt (fenomenul Runge).</span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Liniar:</span> Conectează nodurile prin segmente de dreaptă. Curba rezultată este continuă, dar nu netedă (are &quot;colțuri&quot;).</li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Pătratic / Cubic:</span> Folosește polinoame de gradul 2 sau 3 pe fiecare sub-interval. Spline-urile cubice sunt cele mai populare, deoarece asigură continuitatea curbei, a pantei (prima derivată) și a curburii (a doua derivată) în fiecare nod, rezultând o curbă foarte netedă.<br /></li></ul>\n"
"<p style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:1; text-indent:0px;\"><span style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt; font-weight:600;\">Ghid de Utilizare</span></p>\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Introduceți Intervalul:</span> Stabiliți intervalul de afișare a graficului.</li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Setați Numărul de Noduri:</span> Introduceți numărul total de puncte (noduri) prin care va trece curba spline.</li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Introduceți Nodurile:</span> Completați tabelul <span style=\" font-family:\'monospace\';\">Variabile</span> cu coordonatele <span style=\" font-family:\'monospace\';\">X</span> și <span style=\" font-family:\'monospace\';\">Y</span> ale fiecărui nod.</li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Alegeți Tipul de Spline:</span> Selectați una dintre opțiunile: \n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\">\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'monospace\';\">Liniar</span></li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'monospace\';\">Pătratic</span></li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'monospace\';\">Cubic</span></li></ul></li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Calculați:</span> Apăsați butonul <span style=\" font-weight:600;\">&quot;Calculează&quot;</span>.</li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Vizualizați Rezultatele:</span> \n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\">\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'monospace\';\">Output F(X)</span>: Va afișa setul de ecuații polinomiale care definesc curba spline pe fiecare sub-interval.</li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'monospace\';\">Output Error</span>: Poate oferi informații despre eroare, dacă este cazul.</li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Graficul din dreapta va afișa curba spline netedă care trece prin toate nodurile specificate.</li></ul></li></ol></body></html>"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainFrame", "Interpolare Spline"))
        self.textEdit_2.setHtml(_translate("MainFrame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt; font-weight:600;\">Tema Proiectului</span></h3>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\">Tema proiectului este </span><span style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt; font-weight:600;\">&quot;</span><span style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt; font-weight:600; font-style:italic;\">Polinoame de aproximare si de interpolare</span><span style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt; font-weight:600;\">&quot;</span><span style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\">.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\">Proiectul își propune să ofere un instrument educațional interactiv pentru înțelegerea, compararea și vizualizarea a trei metode fundamentale din analiza numerică:</span></p>\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Aproximarea Bernstein:</span> Explorarea modului în care o funcție continuă poate fi aproximată uniform printr-o serie de polinoame.</li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Interpolarea Lagrange:</span> Demonstrarea construcției unui polinom unic de grad înalt care trece exact printr-un set de puncte predefinite.</li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Interpolarea Spline:</span> Ilustrarea unei metode mai flexibile de interpolare, care utilizează polinoame de grad redus pe sub-intervale pentru a crea o curbă netedă, evitând problemele polinoamelor de grad înalt.</li></ol>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\">Aplicația servește ca un laborator virtual unde utilizatorii pot experimenta cu diferiți parametri (grad, noduri, tipuri de spline) și pot observa instantaneu efectele acestora atât numeric, cât și grafic.</span></p>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt; font-weight:600;\">Cerințe:</span></h3>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Interfață Grafică (GUI):</span>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\">\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Aplicația trebuie să aibă o interfață grafică intuitivă, organizată pe tab-uri (file) pentru fiecare metodă implementată.</li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Trebuie să existe o zonă dedicată pentru introducerea datelor de intrare și o zonă separată pentru vizualizarea grafică a rezultatelor.</li></ul></li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Modulul &quot;Aproximare Bernstein&quot;:</span>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\">\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Să permită utilizatorului să definească un interval <span style=\" font-family:\'monospace\';\">[a, b]</span>.</li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Să permită introducerea gradului <span style=\" font-family:\'monospace\';\">n</span> al polinomului.</li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Să permită calculul valorii aproximate într-un punct <span style=\" font-family:\'monospace\';\">x</span> specificat.</li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Să afișeze numeric valoarea calculată și eroarea de aproximare.</li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Să reprezinte grafic funcția originală și polinomul de aproximare.</li></ul></li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Modulul &quot;Interpolare Lagrange&quot;:</span>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\">\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Să permită utilizatorului să specifice numărul de noduri de interpolare.</li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Să ofere posibilitatea de a introduce coordonatele <span style=\" font-family:\'monospace\';\">(x, y)</span> pentru fiecare nod într-un tabel.</li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Să calculeze și să afișeze forma analitică a polinomului Lagrange rezultat.</li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Să traseze grafic nodurile și curba polinomului care trece prin ele.</li></ul></li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Modulul &quot;Interpolare Spline&quot;:</span>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\">\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Să permită introducerea unui set de noduri de interpolare <span style=\" font-family:\'monospace\';\">(x, y)</span>.</li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Să ofere utilizatorului opțiunea de a alege tipul de interpolare spline (Liniar, Pătratic, Cubic).</li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Să calculeze și să afișeze ecuațiile polinoamelor de pe fiecare sub-interval.</li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Să reprezinte grafic curba spline netedă care unește nodurile.</li></ul></li>\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Modulul &quot;Help&quot;:</span>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\">\n"
"<li style=\" font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Să includă o secțiune de ajutor care să explice noțiunile teoretice, formulele matematice și ghidul de utilizare pentru fiecare metodă.</li></ul></li></ul>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:1; text-indent:0px; font-family:\'Fira Sans Semi-Light\'; font-size:14pt;\"><br /></p></body></html>"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainFrame", "Despre"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainFrame", "Help"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainFrame = QtWidgets.QMainWindow()
    ui = Ui_MainFrame()
    ui.setupUi(MainFrame)
    MainFrame.show()
    sys.exit(app.exec_())
